books/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import logout
from mybooks import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', views.CustomLoginView.as_view(), name='login'),
    url(r'^$', views.main_page, name='main_page'),
    url(r'^add-book/$', views.add_book_page, name='add_book'),
    url(r'^book/(?P<book_id>\d+)/$', views.book_page, name='single_book'),
    url(r'^logout/$', views.CustomLogoutView.as_view(), name='logout'),
    url(r'^post/$', view.Post, name='post'),
    url(r'^messages/$', views.Messages, name='messages'),
]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mybooks/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models

FANTASY = 0
ACTION = 1
ADVENTURE = 2
STRATEGY = 3
HORROR = 4
RPG = 5
SPORT = 6
SHOOTER = 7


class Base(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    edited = models.DateTimeField(auto_now_add=False, auto_now=True)
    author = models.ForeignKey(User, verbose_name='Developer')

    class Meta:
        abstract = True


class Book(Base):

    class Meta:
        ordering = ('name', 'created')
        verbose_name = u'Книжка'
        verbose_name_plural = u'Книжки'

    GENRES = (
        (FANTASY, 'fantasy'),
        (ACTION, 'action'),
        (ADVENTURE, 'adventure'),
        (STRATEGY, 'strategy'),
        (HORROR, 'horror'),
        (RPG, 'rpg'),
        (SPORT, 'sport'),
        (SHOOTER, 'shooter'),
    )
    name = models.CharField(max_length=200, db_index=True)
    description = models.TextField(verbose_name=u'About game')
    year = models.PositiveSmallIntegerField()
    img = models.ImageField(upload_to='books/', null=True, blank=True)
    genre = models.SmallIntegerField(choices=GENRES, default=0)
    publisher = models.CharField(max_length=255, null=True, blank=True)
    url = models.URLField(null=True, blank=True)
    approved = models.BooleanField(default=False)
    def __str__(self):
        return self.name


class Boo(Base):
    name = models.CharField(max_length=200, db_index=True)

class Chat(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)
    message = models.CharField(max_length=200)

    def __unicode__(self):
        return self.message

books/forms.py
# coding=utf-8
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.forms.extras import SelectDateWidget


class BootstrapFormMixin:
    def __init__(self):
        for field_name, field in self.fields.iteritems():
            if not isinstance(field.widget, (forms.TextInput, SelectDateWidget, forms.NumberInput, forms.URLInput,
                                             forms.Textarea, forms.Select, forms.FileInput)):
                continue
            attrs = field.widget.attrs
            if 'class' in attrs:
                if attrs['class']:
                    attrs['class'] += ' '
            else:
                attrs['class'] = ''
            attrs['class'] += 'form-control'


class LoginForm(AuthenticationForm, BootstrapFormMixin):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        BootstrapFormMixin.__init__(self)

    def clean(self):
        has_error = False
        try:
            super(LoginForm, self).clean()
        except forms.ValidationError:
            has_error = True
        if has_error or self.errors or self.user_cache:
            self._errors.clear()
            raise forms.ValidationError(u'Неправильно введений email або пароль')

mybooks/forms.py
from django import forms

from books.forms import BootstrapFormMixin
from mybooks.models import Book


class BookAddForm(forms.ModelForm, BootstrapFormMixin):

    class Meta:
        model = Book
        exclude = ('approved',)

    def __init__(self, *args, **kwargs):
        super(BookAddForm, self).__init__(*args, **kwargs)
        BootstrapFormMixin.__init__(self)
        self.fields['description'].widget.attrs['rows'] = 5

mybooks/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.views import LoginView, LogoutView


from mybooks.forms import BookAddForm
from mybooks.models import Book
from books.forms import LoginForm


def main_page(request):
    search = request.GET.get('search')
    if search:
        books = Book.objects.filter(name__icontains=search)
    else:
        books = Book.objects.filter(approved=True)
    return render(request, 'main.html', {'games': books, 'search': search if search else ''})


def add_book_page(request):
    form = BookAddForm((request.POST or None), (request.FILES or None))
    added = False
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            added = True
    return render(request, 'add_book_form.html', {'form': form, 'added': added})


def book_page(request, book_id):
    game = get_object_or_404(Book, id=book_id)
    return render(request, 'single_book.html', {'game': game})

# def login_view(request):
#     if request.user.is_authenticated():
#         return redirect('main_page')
#     return login(request, 'login.html', authenticated_form=LoginForm)

class CustomLoginView(LoginView):
    template_name = 'login.html'

class CustomLogoutView(LogoutView):
    next_page = '/'

templates/add_book_form.html
{% extends 'base.html' %}

{% block content %}
    <h2>Request game</h2>
    {% if added %}
        <div class="alert alert-success" role="alert">
          Congratulations your game has been requested!
        </div>
    {% endif %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group{% if field.errors %} is-invalid{% endif %}">
                <label for="{{ field.id_for_label }}" class="control-label">{{ field.label }}</label>
                {{ field }}
            </div>
        {% endfor %}
        <button class="btn btn-success float-right" type="submit">Add</button>
    </form>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</head>
<body style="background-color: #d6d6c2;">
    <div class="container">
        {% include 'navbar.html' %}
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

templates/login.html
{% extends 'base.html' %}

{% block content %}
    <div class='row'>
        <form action="{% url 'login' %}" method="post">
            {% csrf_token %}
            {% for field in form%}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}" class="control-label">
                        {{ field.label }}
                    </label>
                    {{ field }}
                </div>
            {% endfor %}
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="login">
            </div>
        </form>
    </div>
{% endblock %}

templates/logout.html
<h1>logout</h1>

templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="row">
    {% for game in games %}
        <div class="col-4">
            <div class="card mb-4" style="width: 18rem;">
            <img style="height: 145px" class="card-img-top" src="{% if game.img %}{{ game.img.url }}{% else %}{% static 'img/default_book.jpg' %}{% endif %}" alt="Card image cap">
              <div class="card-body">
                <h6 class="card-title"><a href="{% url 'single_book' game.id %}">{{ game.name }}</a></h6>
                <p class="card-text">
                    <b>Genre:</b> <span>{{ game.get_genre_display }}</span>
                </p>
              </div>
            </div>
        </div>
    {% empty %}
        <div class="col-12">
            <div class="alert alert-warning text-center" role="alert">
                Game not found :(
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Games</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'add_book' %}">Request game</a>
      </li>
    </ul>
    <ul class="navbar-nav float-right">
      {% if not request.user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      {% else %}
        <li class="nav-item mr-2">
          <b>Hello {{request.user.username }}</b>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
      {% endif %}
    </ul>
     <form class="form-inline" action="{% url 'main_page' %}">
      <input class="form-control mr-sm-2" type="search" name="search" placeholder="Search" aria-label="Search" value="{{ search }}">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<br>

templates/single_book.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <h2>{{ book.name }}</h2>
            <img style="width: 300px; height: 155px;" class="card-img-top float-right" src="{% if game.img %}{{ game.img.url }}{% else %}{% static 'img/default_book.jpg' %}{% endif %}" alt="Card image cap">
            <ul>
                {% if game.genre %}
                    <li><b>Genre:</b> {{ game.get_genre_display }}</li>
                {% endif %}
                {% if game.publisher %}
                    <li><b>Publisher:</b> {{ game.publisher }}</li>
                {% endif %}
                {% if game.year %}
                    <li><b>Year:</b> {{ game.year }}</li>
                {% endif %}
                {% if game.developer %}
                    <li><b>=Developer</b> {{ game.author.username }}</li>
                {% endif %}
                {% if game.url %}
                    <li><b>Buy:</b> <a href="{{ game.url }}">here</a></li>
                {% endif %}
            </ul>
            {% if game.description %}
                <span><b>Description:</b></span>
                <p>{{ game.description }}</p>
            {% endif %}
        </div>
    </div>
{% endblock %}